version: "3.8"

services:
  backend:
    image: backedn:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9001:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
    depends_on:
      - db
      - rabbitmq
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    image: fontend:latest
    build:
      context: ./form-quack-ui
      dockerfile: Dockerfile
    ports:
      - "9000:3000"
    environment:
      API_URL: http://backend:8080
      PUBLIC_APP_DOMAIN: https://formquack.oswinjerome.in
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    networks:
      - app-network
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5673:5672" # RabbitMQ port
      - "15673:15672" # Management console port
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
