spring:
  application:
    name: openAnalytics

  datasource:
    url: jdbc:postgresql://localhost:5432/openAnalytics
    username: oswinjerome
    password: password

  flyway:
    enabled: true
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    user:
      name: user
      password: password


server:
  port: 8080